<a href="https://colab.research.google.com/github/OsbenVizcarra/Programacion_101/blob/main/Practica_N%C2%B0_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Practica N° 03**

**Pregunta 1:**

*   Crea un array unidimensional que contenga los números primos entre 1 y 50.
*   Convierte el array unidimensional anterior en una matriz de forma (n,2), donde n es el número adecuado de filas. Si es necesario, agrega ceros al final del array para completar la matriz.
*   Calcula la suma de cada fila y crea un nuevo array que contenga estos valores.

In [10]:
import numpy as np

def es_primo(n):
  if n <= 1:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True

primos = [num for num in range(2, 51) if es_primo(num)]
primos_array = np.array(primos)

num_primos = len(primos_array)
n = (num_primos + 1) // 2
padding = n * 2 - num_primos

padded_primos = np.pad(primos_array, (0, padding), 'constante')
primos_matriz = padded_primos.reshape(n, 2)

row_sums = np.sum(primos_matriz, axis=1)

print("Array de números primos:")
print(primos_array)
print("\nMatriz de números primos:")
print(primos_matriz)
print("\nSuma de cada fila:")
row_sums

Array de números primos:
[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47]

Matriz de números primos:
[[ 2  3]
 [ 5  7]
 [11 13]
 [17 19]
 [23 29]
 [31 37]
 [41 43]
 [47  0]]

Suma de cada fila:


array([ 5, 12, 24, 36, 52, 68, 84, 47])

**Pregunta 2:**

*   Crea un array bidimensional de forma (4, 4) que contenga números enteros aleatorios entre 1 y 100.
*   Cambia el tipo de datos del array a float64 y divide todos los elementos por 3.7.
*   Calcula y muestra las siguientes propiedades del array resultante:

Dimensiones (ndim),
Forma (shape),
Tamaño total (size),
Tipo de datos (dtype).

In [11]:
import numpy as np

array_2d = np.random.randint(1, 101, size=(4, 4))

array_float = array_2d.astype(np.float64) / 3.7

print("Dimensiones:", array_float.ndim)
print("Forma:", array_float.shape)
print("Tamaño total:", array_float.size)
print("Tipo de datos:", array_float.dtype)

Dimensiones: 2
Forma: (4, 4)
Tamaño total: 16
Tipo de datos: float64


**Pregunta 3:**

*   Crea un array x que contenga 100 valores equiespaciados entre -10 y 10.
*   Calcula el valor de la función f(x)=e**(-x**2) para cada elemento de x.
*   Encuentra el valor máximo y mínimo de f(x) y las posiciones en el array donde ocurren.




In [13]:
import numpy as np

x = np.linspace(-10, 10, 100)
fx = np.exp(-x**2)

valor_maximo = np.max(fx)
posicion_maximo = np.argmax(fx)

valor_minimo = np.min(fx)
posicion_minimo = np.argmin(fx)

print("Valor máximo de f(x):", valor_maximo)
print("Posición del valor máximo:", posicion_maximo)
print("Valor mínimo de f(x):", valor_minimo)
print("Posición del valor mínimo:", posicion_minimo)

Valor máximo de f(x): 0.9898488339361309
Posición del valor máximo: 49
Valor mínimo de f(x): 3.720075976020836e-44
Posición del valor mínimo: 0


**Pregunta 4: Indexación y Slicing Avanzado.**

Dado el siguiente array bidimensional:
array = np.arange(1, 101). reshape(10, 10)

*   Extrae un subarray que contenga los elementos en posiciones pares de filas y columnas (es decir, filas y columnas con índices 0, 2, 4, 6, 8).
*   Reemplaza todos los elementos que son múltiplos de 3 por -1.
*   Utiliza indexación avanzada para extraer todos los números primos del array original y crea un nuevo array con estos valores.


In [14]:
import numpy as np

array = np.arange(1, 101).reshape(10, 10)

subarray = array[::2, ::2]

array[array % 3 == 0] = -1

def es_primo(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

primos_indices = np.array([i for i in range(1,101) if es_primo(i)])
primos_array = array[np.where(np.isin(array, primos_indices))]

print("Subarray con posiciones pares:")
print(subarray)
print("\nArray con múltiplos de 3 reemplazados por -1:")
print(array)
print("\nArray de números primos:")
primos_array

Subarray con posiciones pares:
[[ 1 -1  5  7 -1]
 [-1 23 25 -1 29]
 [41 43 -1 47 49]
 [61 -1 65 67 -1]
 [-1 83 85 -1 89]]

Array con múltiplos de 3 reemplazados por -1:
[[  1   2  -1   4   5  -1   7   8  -1  10]
 [ 11  -1  13  14  -1  16  17  -1  19  20]
 [ -1  22  23  -1  25  26  -1  28  29  -1]
 [ 31  32  -1  34  35  -1  37  38  -1  40]
 [ 41  -1  43  44  -1  46  47  -1  49  50]
 [ -1  52  53  -1  55  56  -1  58  59  -1]
 [ 61  62  -1  64  65  -1  67  68  -1  70]
 [ 71  -1  73  74  -1  76  77  -1  79  80]
 [ -1  82  83  -1  85  86  -1  88  89  -1]
 [ 91  92  -1  94  95  -1  97  98  -1 100]]

Array de números primos:


array([ 2,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61,
       67, 71, 73, 79, 83, 89, 97])

**Pregunta 5:**

*   Crea tres arrays unidimensionales de longitud 5 con números aleatorios entre 0 y 1.
*   Combina estos arrays para formar una matriz de forma (5, 3).
*   Agrega una columna de unos al principio de la matriz resultante, obteniendo una matriz de forma (5, 4).
*   Reordena las columnas de la matriz para que la columna de unos esté al final.



In [25]:
array1 = np.random.rand(5)
array2 = np.random.rand(5)
array3 = np.random.rand(5)

matriz = np.column_stack((array1, array2, array3))

unos = np.ones((5, 1))
matriz_con_unos = np.concatenate((unos, matriz), axis=1)

matriz_reordenada = np.concatenate((matriz_con_unos[:, 1:], matriz_con_unos[:, 0:1]), axis=1)

print("1er array:", array1)
print("2do array:", array2)
print("3er array:", array3)
print("\nMatriz original (5x3):\n", matriz)
print("\nMatriz con columna de unos al principio (5x4):\n", matriz_con_unos)
print("\nMatriz con columna de unos al final (5x4):\n", matriz_reordenada)

1er array: [0.27916956 0.14649582 0.41374976 0.23003958 0.87673847]
2do array: [0.57002033 0.7571999  0.22553129 0.15836325 0.7210654 ]
3er array: [0.73564875 0.09503752 0.84310404 0.33148702 0.07526237]

Matriz original (5x3):
 [[0.27916956 0.57002033 0.73564875]
 [0.14649582 0.7571999  0.09503752]
 [0.41374976 0.22553129 0.84310404]
 [0.23003958 0.15836325 0.33148702]
 [0.87673847 0.7210654  0.07526237]]

Matriz con columna de unos al principio (5x4):
 [[1.         0.27916956 0.57002033 0.73564875]
 [1.         0.14649582 0.7571999  0.09503752]
 [1.         0.41374976 0.22553129 0.84310404]
 [1.         0.23003958 0.15836325 0.33148702]
 [1.         0.87673847 0.7210654  0.07526237]]

Matriz con columna de unos al final (5x4):
 [[0.27916956 0.57002033 0.73564875 1.        ]
 [0.14649582 0.7571999  0.09503752 1.        ]
 [0.41374976 0.22553129 0.84310404 1.        ]
 [0.23003958 0.15836325 0.33148702 1.        ]
 [0.87673847 0.7210654  0.07526237 1.        ]]


**Pregunta 6:**

*   Crea una matriz simétrica positiva definida de tamaño 3x3.
*   Calcula sus valores y vectores propios (eigenvalores y eigenvectores).
*   Verifica que la multiplicación de la matriz original por un vector propio es igual al producto del eigenvalor correspondiente por el vector propio.

In [39]:
matriz = np.array([[4, 1, 1],
                   [1, 4, 1],
                   [1, 1, 4]])

valores_propios, vectores_propios = np.linalg.eig(matriz)

for i in range(3):
  vector_propio = vectores_propios[:, i]
  valor_propio = valores_propios[i]

  producto_matriz_vector = np.dot(matriz, vector_propio)
  producto_valor_vector = valor_propio * vector_propio

  print(f"Vector propio {i+1}: {vector_propio}")
  print(f"Valor propio {i+1}: {valor_propio}")
  print(f"Matriz * Vector Propio: {producto_matriz_vector}")
  print(f"Valor Propio * Vector Propio: {producto_valor_vector}")
  print("-" * 20)

Vector propio 1: [-0.57735027 -0.57735027 -0.57735027]
Valor propio 1: 5.999999999999998
Matriz * Vector Propio: [-3.46410162 -3.46410162 -3.46410162]
Valor Propio * Vector Propio: [-3.46410162 -3.46410162 -3.46410162]
--------------------
Vector propio 2: [-0.81649658  0.40824829  0.40824829]
Valor propio 2: 2.9999999999999982
Matriz * Vector Propio: [-2.44948974  1.22474487  1.22474487]
Valor Propio * Vector Propio: [-2.44948974  1.22474487  1.22474487]
--------------------
Vector propio 3: [-0.15430335 -0.6172134   0.77151675]
Valor propio 3: 2.9999999999999996
Matriz * Vector Propio: [-0.46291005 -1.8516402   2.31455025]
Valor Propio * Vector Propio: [-0.46291005 -1.8516402   2.31455025]
--------------------


**Pregunta 7:**

*   Construye un sistema de ecuaciones lineales con tres ecuaciones y tres incógnitas donde la matriz de coeficientes es singular (no invertible).
*   Intenta resolver el sistema utilizando np.linalg.solve() y explica el resultado obtenido.

In [34]:
import numpy as np

A = np.array([[1, 2, 3],
              [2, 4, 6],
              [3, 6, 9]])

b = np.array([6, 12, 18])

try:
    x = np.linalg.solve(A, b)
    print("Solución del sistema:")
    print(x)
except np.linalg.LinAlgError as e:
    print(f"Error: {e}")
    print("\nLa matriz de coeficientes es singular, por lo que no tiene inversa única y el sistema no tiene solución única o no tiene solución.")

Error: Singular matrix

La matriz de coeficientes es singular, por lo que no tiene inversa única y el sistema no tiene solución única o no tiene solución.


**Pregunta 8:**

*   Crea un array de forma (4, 4, 4) con números enteros aleatorios entre 0 y 100.
*   Calcula la suma a lo largo del eje 0, obteniendo un array de forma (4, 4).
*   Calcula el promedio a lo largo del eje 1, obteniendo un array de forma (4, 4).
*   Reestructura el array original en una nueva forma de (8, 8) sin perder datos.

In [40]:
array_3d = np.random.randint(0, 101, size=(4, 4, 4))

suma_eje0 = np.sum(array_3d, axis=0)

promedio_eje1 = np.mean(array_3d, axis=1)

array_reestructurado = array_3d.reshape(8, 8)

print("Array original (4, 4, 4):\n", array_3d)
print("\nSuma a lo largo del eje 0 (4, 4):\n", suma_eje0)
print("\nPromedio a lo largo del eje 1 (4, 4):\n", promedio_eje1)
print("\nArray reestructurado (8, 8):\n", array_reestructurado)

Array original (4, 4, 4):
 [[[29 68 91 83]
  [46 67 94 38]
  [48 60  0  5]
  [91 72  7 40]]

 [[69 79 18  8]
  [78 48 69 66]
  [15 41 94 37]
  [ 2 34 50 35]]

 [[95 74 66 13]
  [67  6 49 19]
  [40 61 98 24]
  [78 72 57 82]]

 [[45 89 39 64]
  [35 93 69 66]
  [10 52 15 87]
  [21 63 10 48]]]

Suma a lo largo del eje 0 (4, 4):
 [[238 310 214 168]
 [226 214 281 189]
 [113 214 207 153]
 [192 241 124 205]]

Promedio a lo largo del eje 1 (4, 4):
 [[53.5  66.75 48.   41.5 ]
 [41.   50.5  57.75 36.5 ]
 [70.   53.25 67.5  34.5 ]
 [27.75 74.25 33.25 66.25]]

Array reestructurado (8, 8):
 [[29 68 91 83 46 67 94 38]
 [48 60  0  5 91 72  7 40]
 [69 79 18  8 78 48 69 66]
 [15 41 94 37  2 34 50 35]
 [95 74 66 13 67  6 49 19]
 [40 61 98 24 78 72 57 82]
 [45 89 39 64 35 93 69 66]
 [10 52 15 87 21 63 10 48]]


**Pregunta 9:**

Se define una secuencia de números donde cada elemento es el factorial del índice correspondiente. Formalmente:

a n = n! para n = 1,2,...,10

*   Usando NumPy, crea un array que contenga los primeros 10 elementos de esta secuencia sin utilizar bucles explícitos.
*   Calcula la suma de todos los elementos del array creado.
*   Dado que los factoriales pueden ser números muy grandes, cambia el tipo de datos del array a object para manejar enteros arbitrariamente grandes y recalcula la suma.

In [59]:
import numpy as np
import math

def factorial(n):
    return math.factorial(n)

factoriales = np.array([factorial(i) for i in range(11)])

suma_factoriales = np.sum(factoriales)

factoriales_obj = np.array([factorial(i) for i in range(11)], dtype=object)
suma_factoriales_obj = np.sum(factoriales_obj)

print("Suma de factoriales:", suma_factoriales)
print("Secuencia de factoriales (object type):", factoriales_obj)

Suma de factoriales: 4037914
Secuencia de factoriales (object type): [1 1 2 6 24 120 720 5040 40320 362880 3628800]


**Pregunta 10:**

*   Simula un conjunto de datos que represente las alturas (en cm) de 500 personas, siguiendo una distribución normal con media 170 y desviación estándar 10.
*   Encuentra cuántas personas miden más de 180 cm y menos de 160 cm.
*   Normaliza los datos de altura para que tengan media 0 y desviación estándar 1.



In [61]:
import numpy as np

alturas = np.random.normal(170, 10, 500)

mas_180 = np.sum(alturas > 180)
menos_160 = np.sum(alturas < 160)

alturas_normalizadas = (alturas - np.mean(alturas)) / np.std(alturas)

print("Número de personas con altura superior a 180 cm:", mas_180)
print("Número de personas con altura inferior a 160 cm:", menos_160)
print("\nPrimeros 10 datos de alturas normalizadas:", alturas_normalizadas[:10])

Número de personas con altura superior a 180 cm: 74
Número de personas con altura inferior a 160 cm: 80

Primeros 10 datos de alturas normalizadas: [-1.37367429  1.69241328 -0.4932528   2.09986187  0.29321437 -0.06464788
  0.70640838 -1.45717401 -1.01711083  1.5803254 ]
