<a href="https://colab.research.google.com/github/OsbenVizcarra/Programacion_101/blob/main/01_Introduccion_a_Python/03_Estructuras_de_datos_parte2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >


<h1 align=center><font size = 5>ESTRUCTURAS DE DATOS - PARTE 2
</font></h1>

---


**Tabla de Contenidos**

- Diccionarios
- Sets
- Matrices

---

## 1. Diccionarios

**Concepto:**

Un diccionario es una estructura de datos que almacena pares clave-valor. Las claves deben ser únicas y se utilizan para acceder a los valores asociados.

### Ejemplo 1.1: Creación de Diccionarios y Acceso a Elementos


In [1]:
# Crear un diccionario
persona = {'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}
print(persona)

{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}


In [2]:
# Acceder a un valor
print("Nombre:", persona['nombre'])
print("Ciudad:", persona.get('ciudad'))


Nombre: Ana
Ciudad: Lima


In [3]:

# Añadir un nuevo par clave-valor
persona['profesion'] = 'Ingeniera'
print(persona)



{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima', 'profesion': 'Ingeniera'}


In [4]:
# Eliminar un par clave-valor
del persona['ciudad']
print(persona)

{'nombre': 'Ana', 'edad': 30, 'profesion': 'Ingeniera'}


### Ejemplo 1.2: Métodos Útiles de Diccionarios


In [5]:
# Obtener todas las claves
print(persona.keys())


dict_keys(['nombre', 'edad', 'profesion'])


In [6]:
# Obtener todos los valores
print(persona.values())


dict_values(['Ana', 30, 'Ingeniera'])


In [7]:
# Comprobar si una clave existe en el diccionario
if 'edad' in persona:
    print("La clave 'edad' está en el diccionario.")


La clave 'edad' está en el diccionario.


### Ejercicio 1: Trabajando con Diccionarios

- Crea un diccionario que contenga información sobre un automóvil (marca, modelo, año, color).
- Accede a cada valor usando su clave.
- Añade una clave para el precio del automóvil.
- Elimina la clave del color del automóvil y muestra el diccionario actualizado.
- Usa keys() y values() para imprimir las claves y valores del diccionario.



In [8]:

# Crea un diccionario que contenga información sobre un automóvil (marca, modelo, año, color).
automovil = {'marca': 'MG','modelo': 'HS','año': 2024,'color': 'Gris'}


In [9]:

# Accede a cada valor usando su clave
print("Marca:", automovil['marca'])
print("Modelo:", automovil['modelo'])
print("Año:", automovil['año'])
print("Color:", automovil['color'])


Marca: MG
Modelo: HS
Año: 2024
Color: Gris


In [11]:

# Añade una clave para el precio del automóvil
automovil['precio'] = 25000
print(automovil)


{'marca': 'MG', 'modelo': 'HS', 'año': 2024, 'color': 'Gris', 'precio': 25000}


In [12]:

# Elimina la clave del color del automóvil y muestra el diccionario actualizado
del automovil['color']
print("Diccionario actualizado:", automovil)


Diccionario actualizado: {'marca': 'MG', 'modelo': 'HS', 'año': 2024, 'precio': 25000}


In [13]:

# Usa keys() y values() para imprimir las claves y valores del diccionario
print("Claves:", automovil.keys())
print("Valores:", automovil.values())


Claves: dict_keys(['marca', 'modelo', 'año', 'precio'])
Valores: dict_values(['MG', 'HS', 2024, 25000])


## 2. Sets

Los sets son colecciones de elementos únicos y desordenados. Son útiles para eliminar duplicados o realizar operaciones matemáticas como intersección y unión.

### Ejemplo 2.1: Creación y Modificación de Sets

In [14]:

# Crear un set
numeros = {1, 2, 3, 4, 5}
print(numeros)


{1, 2, 3, 4, 5}


In [15]:

# Añadir elementos
numeros.add(6)
print(numeros)


{1, 2, 3, 4, 5, 6}


In [16]:

# Eliminar un elemento
numeros.remove(3)
print(numeros)


{1, 2, 4, 5, 6}


### Ejemplo 2.2: Operaciones de Conjuntos


In [18]:

# Crear otro set
otro_set = {4, 5, 6, 7}


In [19]:

# Unión de sets (todos los elementos)
union = numeros.union(otro_set)
print("Unión:", union)


Unión: {1, 2, 4, 5, 6, 7}


In [20]:

# Intersección de sets (elementos comunes)
interseccion = numeros.intersection(otro_set)
print("Intersección:", interseccion)


Intersección: {4, 5, 6}


### Ejercicio 2: Operaciones con Sets

- Crea dos sets de números: uno con números del 1 al 10 y otro con números del 5 al 15.
- Encuentra la intersección y unión de ambos sets.
- Elimina un número del primer set.
- Usa un set para almacenar los nombres de tus amigos. Asegúrate de que no haya duplicados.

In [21]:

# Crea dos sets de números: uno con números del 1 al 10 y otro con números del 5 al 15.
set1 = set(range(1, 11))
set2 = set(range(5, 16))


In [22]:

# Encuentra la intersección y unión de ambos sets.
interseccion = set1.intersection(set2)
union = set1.union(set2)
print("Intersección:", interseccion)
print("Unión:", union)


Intersección: {5, 6, 7, 8, 9, 10}
Unión: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}


In [23]:

# Elimina un número del primer set.
set1.remove(5)
print("Set1 actualizado:", set1)


Set1 actualizado: {1, 2, 3, 4, 6, 7, 8, 9, 10}


In [25]:

# Usa un set para almacenar los nombres de tus amigos. Asegúrate de que no haya duplicados.
nombres_amigos = ["Juan", "Maria", "Pedro", "Ana", "Luis", "Juan", "Maria"]
amigos = set(nombres_amigos)

print("Los nombres de mis amigos son:",nombres_amigos)
print("Los nombres de mis amigos sin duplicados son:", amigos)


Los nombres de mis amigos son: ['Juan', 'Maria', 'Pedro', 'Ana', 'Luis', 'Juan', 'Maria']
Los nombres de mis amigos sin duplicados son: {'Ana', 'Pedro', 'Maria', 'Luis', 'Juan'}


## 3. Matrices

En Python, las matrices pueden representarse como listas de listas. Para manipular matrices más avanzadas y realizar cálculos eficientes, utilizamos la librería NumPy.

### Ejemplo 3.1: Matrices con Listas de Listas


In [26]:
# Crear una matriz 3x3 con listas anidadas
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(matriz)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [27]:
# Acceder a elementos de la matriz
print("Elemento en [1][1]:", matriz[1][1])


Elemento en [1][1]: 5


In [28]:
# Modificar un elemento
matriz[2][0] = 10
print(matriz)

[[1, 2, 3], [4, 5, 6], [10, 8, 9]]


### Ejemplo 3.2: Manipulación de Matrices con NumPy


In [29]:
import numpy as np

# Crear una matriz 3x3 con NumPy
matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matriz_np)




[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
# Sumar 10 a cada elemento
print(matriz_np + 10)



[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [31]:
# Multiplicar cada elemento por 2
print(matriz_np * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


### Ejercicio 3: Operaciones con Matrices

- Crea una matriz 3x3 usando listas de listas.
- Modifica un valor de la matriz y muestra la matriz actualizada.
- Usa NumPy para crear una matriz 4x4 con números aleatorios enteros.
- Realiza una operación de suma con la matriz (suma 5 a cada elemento).
- Multiplica los elementos de la matriz por 2 usando NumPy.

In [33]:

# Crea una matriz 3x3 usando listas de listas.
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print("Matriz original:", matriz)


Matriz original: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [34]:

# Modifica un valor de la matriz y muestra la matriz actualizada.
matriz[1][1] = 10
print("\nMatriz actualizada:", matriz)



Matriz actualizada: [[1, 2, 3], [4, 10, 6], [7, 8, 9]]


In [37]:

# Usa NumPy para crear una matriz 4x4 con números aleatorios enteros.
matriz_np = np.random.randint(0, 10, size=(4, 4))
print("Matriz NumPy con números aleatorios:")
print(matriz_np)


Matriz NumPy con números aleatorios:
[[2 9 4 6]
 [3 1 0 9]
 [5 7 2 8]
 [8 0 9 0]]


In [41]:

# Realiza una operación de suma con la matriz (suma 5 a cada elemento).
matriz_np_suma = matriz_np + 5
print("Matriz suma:")
print(matriz_np_suma)


Matriz suma:
[[ 7 14  9 11]
 [ 8  6  5 14]
 [10 12  7 13]
 [13  5 14  5]]


In [43]:

# Multiplica los elementos de la matriz por 2 usando NumPy.
matriz_np_multiplicada = matriz_np * 2
print("Matriz NumPy con elementos multiplicados por 2:")
print(matriz_np_multiplicada)


Matriz NumPy con elementos multiplicados por 2:
[[ 4 18  8 12]
 [ 6  2  0 18]
 [10 14  4 16]
 [16  0 18  0]]


## 4. Desafío


Eres el encargado de un almacén de productos electrónicos. Tienes un registro de ventas semanales para teléfonos, laptops y tabletas. Necesitas analizar las ventas para mejorar la gestión.

- Crea tres listas: una para teléfonos, otra para laptops y otra para tabletas con las ventas de cada día durante una semana.
- Usa slicing para obtener las ventas de los últimos 3 días de cada producto.
- Usa listas por comprensión para calcular el total de ventas de cada producto y el promedio de ventas diarias.
- Clasifica los productos en "ventas altas" o "ventas bajas" según si el promedio de ventas es mayor o menor a 5.

Instrucciones:
Usa sum() y len() para calcular el total de ventas y el promedio.
Clasifica las ventas usando listas por comprensión.

In [51]:

# Crea tres listas: una para teléfonos, otra para laptops y otra para tabletas con las ventas de cada día durante una semana.
telefonos = [10, 12, 8, 15, 11, 9, 13]
laptops = [5, 7, 6, 8, 9, 4, 6]
tabletas = [7, 9, 8, 10, 12, 6, 8]


In [47]:

# Usa slicing para obtener las ventas de los últimos 3 días de cada producto.
ultimos_3_dias_telefonos = telefonos[-3:]
ultimos_3_dias_laptops = laptops[-3:]
ultimos_3_dias_tabletas = tabletas[-3:]

print("Ventas de los últimos 3 días de teléfonos:", ultimos_3_dias_telefonos)
print("Ventas de los últimos 3 días de laptops:", ultimos_3_dias_laptops)
print("Ventas de los últimos 3 días de tabletas:", ultimos_3_dias_tabletas)


Ventas de los últimos 3 días de teléfonos: [11, 9, 13]
Ventas de los últimos 3 días de laptops: [9, 4, 6]
Ventas de los últimos 3 días de tabletas: [12, 6, 8]


In [49]:

# Usa listas por comprensión para calcular el total de ventas de cada producto y el promedio de ventas diarias.
total_ventas_telefonos = sum(x for x in telefonos)
promedio_ventas_telefonos = total_ventas_telefonos / len(telefonos)
print("Total de ventas de teléfonos:", total_ventas_telefonos)
print("Promedio de ventas diarias de teléfonos:", promedio_ventas_telefonos)

total_ventas_laptops = sum(x for x in laptops)
promedio_ventas_laptops = total_ventas_laptops / len(laptops)
print("Total de ventas de laptops:", total_ventas_laptops)
print("Promedio de ventas diarias de laptops:", promedio_ventas_laptops)

total_ventas_tabletas = sum(x for x in tabletas)
promedio_ventas_tabletas = total_ventas_tabletas / len(tabletas)
print("Total de ventas de tabletas:", total_ventas_tabletas)
print("Promedio de ventas diarias de tabletas:", promedio_ventas_tabletas)


Total de ventas de teléfonos: 78
Promedio de ventas diarias de teléfonos: 11.142857142857142
Total de ventas de laptops: 45
Promedio de ventas diarias de laptops: 6.428571428571429
Total de ventas de tabletas: 60
Promedio de ventas diarias de tabletas: 8.571428571428571


In [50]:

# Clasifica los productos en "ventas altas" o "ventas bajas" según si el promedio de ventas es mayor o menor a 5.

ventas_telefonos = "Buenas ventas" if promedio_ventas_telefonos >5 else "Malas ventas"
ventas_laptops = "Buenas ventas" if promedio_ventas_laptops > 5 else "Malas ventas"
ventas_tabletas = "Buenas ventas" if promedio_ventas_tabletas > 5 else "Malas ventas"

print("El nivel de ventas de telefonos:", ventas_telefonos)
print("El nivel de ventas de laptops:", ventas_laptops)
print("El nivel de ventas de tabletas:", ventas_tabletas)


El nivel de ventas de telefonos: Buenas ventas
El nivel de ventas de laptops: Buenas ventas
El nivel de ventas de tabletas: Buenas ventas


---

# Gracias por completar este laboratorio!

---